import { z } from "zod";
import { ResourceConfig } from "../../types/resource";
import { Tables } from "@/integrations/supabase/types";

type CommunityRow = Tables<"communities">;

const communitiesFormSchema = z.object({
  slug: z
    .string()
    .min(1, "Slug is required")
    .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Use lowercase letters, numbers, and hyphens only"),
  name: z.string().min(1, "Name is required"),
  county: z.string().min(1, "County is required"),
  region: z.string().optional(),
  hero_image: z.string().optional(),
  description: z.string().optional(),
  origin_story: z.string().optional(),
  history: z.string().optional(),
  population: z.number().int().optional(),
  established_year: z.string().optional(),
  specialty: z.string().optional(),
  traditional_dress: z.string().optional(),
  adornment_explanation: z.string().optional(),
  leader_name: z.string().optional(),
  leader_title: z.string().optional(),
  contact_email: z.string().optional(),
  contact_phone: z.string().optional(),
  max_daily_visitors: z.number().int().optional(),
  visitor_guidelines: z.string().optional(),
  ecological_knowledge: z.string().optional(),
  lat: z.number().optional(),
  lng: z.number().optional(),
  meta_title: z.string().optional(),
  meta_description: z.string().optional(),
  is_published: z.boolean(),
});

export type CommunitiesFormValues = z.infer<typeof communitiesFormSchema>;

export const communitiesResource: ResourceConfig<CommunityRow, CommunitiesFormValues> = {
  key: "communities",
  table: "communities",
  label: "Community",
  labelPlural: "Communities",
  statusColumn: "is_published",
  basePath: "/admin/communities",
  formSchema: communitiesFormSchema,
  searchColumn: "name",
  defaultSort: { column: "created_at", ascending: false },
  listColumns: [
    { key: "name", header: "Name" },
    { key: "slug", header: "Slug" },
    { key: "county", header: "County" },
    { key: "region", header: "Region" },
    { key: "population", header: "Population" },
  ],
  formFields: [
    {
      kind: "text",
      name: "slug",
      label: "Slug",
      placeholder: "e.g. maasai-mara",
      description: "Lowercase letters, numbers, and hyphens only. Used in the public URL.",
    },
    { kind: "text", name: "name", label: "Name" },
    { kind: "text", name: "county", label: "County" },
    { kind: "text", name: "region", label: "Region (optional)" },
    { kind: "image", name: "hero_image", label: "Hero image" },
    { kind: "textarea", name: "description", label: "Description" },
    { kind: "textarea", name: "origin_story", label: "Origin story" },
    { kind: "textarea", name: "history", label: "History" },
    { kind: "number", name: "population", label: "Population" },
    { kind: "text", name: "established_year", label: "Established year" },
    { kind: "text", name: "specialty", label: "Specialty" },
    { kind: "text", name: "traditional_dress", label: "Traditional dress" },
    { kind: "textarea", name: "adornment_explanation", label: "Adornment explanation" },
    { kind: "text", name: "leader_name", label: "Leader name" },
    { kind: "text", name: "leader_title", label: "Leader title" },
    { kind: "text", name: "contact_email", label: "Contact email" },
    { kind: "text", name: "contact_phone", label: "Contact phone" },
    { kind: "number", name: "max_daily_visitors", label: "Max daily visitors" },
    { kind: "textarea", name: "visitor_guidelines", label: "Visitor guidelines" },
    { kind: "textarea", name: "ecological_knowledge", label: "Ecological knowledge" },
    { kind: "number", name: "lat", label: "Latitude" },
    { kind: "number", name: "lng", label: "Longitude" },
    { kind: "text", name: "meta_title", label: "Meta title" },
    { kind: "textarea", name: "meta_description", label: "Meta description" },
    { kind: "switch", name: "is_published", label: "Published" },
  ],
  toFormValues: (row) => ({
    slug: row?.slug ?? "",
    name: row?.name ?? "",
    county: row?.county ?? "",
    region: row?.region ?? "",
    hero_image: row?.hero_image ?? "",
    description: row?.description ?? "",
    origin_story: row?.origin_story ?? "",
    history: row?.history ?? "",
    population: row?.population ?? undefined,
    established_year: row?.established_year ?? "",
    specialty: row?.specialty ?? "",
    traditional_dress: row?.traditional_dress ?? "",
    adornment_explanation: row?.adornment_explanation ?? "",
    leader_name: row?.leader_name ?? "",
    leader_title: row?.leader_title ?? "",
    contact_email: row?.contact_email ?? "",
    contact_phone: row?.contact_phone ?? "",
    max_daily_visitors: row?.max_daily_visitors ?? 20,
    visitor_guidelines: row?.visitor_guidelines ?? "",
    ecological_knowledge: row?.ecological_knowledge ?? "",
    lat: row?.lat ?? undefined,
    lng: row?.lng ?? undefined,
    meta_title: row?.meta_title ?? "",
    meta_description: row?.meta_description ?? "",
    is_published: row?.is_published ?? false,
  }),
  toRowPayload: (values) => ({ ...values }),
};
