import { z } from "zod";
import { ResourceConfig } from "../../types/resource";
import { Tables } from "@/integrations/supabase/types";

type ExperienceRow = Tables<"experiences">;

const categories = [
  { label: "Cultural", value: "cultural" },
  { label: "Food", value: "food" },
  { label: "Nature", value: "nature" },
  { label: "Adventure", value: "adventure" },
  { label: "Homestay", value: "homestay" },
  { label: "Community", value: "community" },
  { label: "Photography", value: "photography" },
  { label: "Volunteer", value: "volunteer" },
];

const currencies = [
  { label: "USD", value: "USD" },
  { label: "KES", value: "KES" },
  { label: "EUR", value: "EUR" },
  { label: "GBP", value: "GBP" },
];

const skillLevels = [
  { label: "Beginner", value: "beginner" },
  { label: "Moderate", value: "moderate" },
  { label: "Challenging", value: "challenging" },
];

const experiencesFormSchema = z.object({
  title: z.string().min(1, "Title is required"),
  slug: z.string().min(1, "Slug is required"),
  category: z.string().min(1, "Category is required"),
  subcategory: z.string().optional(),
  description: z.string().optional(),
  short_description: z.string().optional(),
  host_name: z.string().min(1, "Host name is required"),
  host_bio: z.string().optional(),
  host_photo: z.string().optional(),
  location_name: z.string().optional(),
  county: z.string().optional(),
  lat: z.number().optional(),
  lng: z.number().optional(),
  duration_minutes: z.number().optional(),
  price_amount: z.number({ invalid_type_error: "Price is required" }),
  price_currency: z.string(),
  price_display: z.string().optional(),
  max_guests: z.number().optional(),
  min_guests: z.number().optional(),
  cover_image: z.string().optional(),
  gallery_images: z.array(z.string()),
  what_to_bring: z.string().optional(),
  what_to_wear: z.string().optional(),
  skill_level: z.string(),
  languages: z.array(z.string()),
  includes: z.array(z.string()),
  accessibility_notes: z.string().optional(),
  is_featured: z.boolean(),
  available_days: z.array(z.string()),
  start_times: z.array(z.string()),
  meta_title: z.string().optional(),
  meta_description: z.string().optional(),
  is_published: z.boolean(),
});

export type ExperiencesFormValues = z.infer<typeof experiencesFormSchema>;

export const experiencesResource: ResourceConfig<ExperienceRow, ExperiencesFormValues> = {
  key: "experiences",
  table: "experiences",
  label: "Experience",
  labelPlural: "Experiences",
  statusColumn: "is_published",
  basePath: "/admin/experiences",
  formSchema: experiencesFormSchema,
  searchColumn: "title",
  defaultSort: { column: "created_at", ascending: false },
  filters: [{ key: "category", label: "Category", type: "select", options: categories }],
  listColumns: [
    { key: "title", header: "Title" },
    { key: "category", header: "Category" },
    { key: "host_name", header: "Host" },
    { key: "location_name", header: "Location" },
    { key: "price_display", header: "Price" },
  ],
  formFields: [
    { kind: "text", name: "title", label: "Title" },
    { kind: "text", name: "slug", label: "Slug", description: "Unique, lowercase-with-hyphens" },
    { kind: "select", name: "category", label: "Category", options: categories },
    { kind: "text", name: "subcategory", label: "Subcategory (optional)" },
    { kind: "textarea", name: "description", label: "Description" },
    { kind: "textarea", name: "short_description", label: "Short description" },
    { kind: "text", name: "host_name", label: "Host name" },
    { kind: "textarea", name: "host_bio", label: "Host bio" },
    { kind: "image", name: "host_photo", label: "Host photo" },
    { kind: "text", name: "location_name", label: "Location name" },
    { kind: "text", name: "county", label: "County" },
    { kind: "number", name: "lat", label: "Latitude" },
    { kind: "number", name: "lng", label: "Longitude" },
    { kind: "number", name: "duration_minutes", label: "Duration (minutes)" },
    { kind: "number", name: "price_amount", label: "Price amount" },
    { kind: "select", name: "price_currency", label: "Price currency", options: currencies },
    { kind: "text", name: "price_display", label: "Price display", placeholder: "e.g. $45" },
    { kind: "number", name: "max_guests", label: "Max guests" },
    { kind: "number", name: "min_guests", label: "Min guests" },
    { kind: "image", name: "cover_image", label: "Cover image" },
    { kind: "gallery", name: "gallery_images", label: "Gallery images" },
    { kind: "textarea", name: "what_to_bring", label: "What to bring" },
    { kind: "text", name: "what_to_wear", label: "What to wear" },
    { kind: "select", name: "skill_level", label: "Skill level", options: skillLevels },
    { kind: "tags", name: "languages", label: "Languages", description: "Comma-separated" },
    { kind: "tags", name: "includes", label: "Includes", description: "Comma-separated" },
    { kind: "textarea", name: "accessibility_notes", label: "Accessibility notes" },
    { kind: "switch", name: "is_featured", label: "Featured" },
    { kind: "tags", name: "available_days", label: "Available days", description: "Comma-separated, e.g. Monday, Tuesday" },
    { kind: "tags", name: "start_times", label: "Start times", description: "Comma-separated, e.g. 09:00, 14:00" },
    { kind: "text", name: "meta_title", label: "Meta title" },
    { kind: "textarea", name: "meta_description", label: "Meta description" },
    { kind: "switch", name: "is_published", label: "Published" },
  ],
  toFormValues: (row) => ({
    title: row?.title ?? "",
    slug: row?.slug ?? "",
    category: row?.category ?? "cultural",
    subcategory: row?.subcategory ?? "",
    description: row?.description ?? "",
    short_description: row?.short_description ?? "",
    host_name: row?.host_name ?? "",
    host_bio: row?.host_bio ?? "",
    host_photo: row?.host_photo ?? "",
    location_name: row?.location_name ?? "",
    county: row?.county ?? "",
    lat: row?.lat ?? 0,
    lng: row?.lng ?? 0,
    duration_minutes: row?.duration_minutes ?? 120,
    price_amount: row?.price_amount ?? 0,
    price_currency: row?.price_currency ?? "USD",
    price_display: row?.price_display ?? "",
    max_guests: row?.max_guests ?? 10,
    min_guests: row?.min_guests ?? 1,
    cover_image: row?.cover_image ?? "",
    gallery_images: row?.gallery_images ?? [],
    what_to_bring: row?.what_to_bring ?? "",
    what_to_wear: row?.what_to_wear ?? "",
    skill_level: row?.skill_level ?? "beginner",
    languages: row?.languages ?? [],
    includes: row?.includes ?? [],
    accessibility_notes: row?.accessibility_notes ?? "",
    is_featured: row?.is_featured ?? false,
    available_days: row?.available_days ?? [],
    start_times: row?.start_times ?? [],
    meta_title: row?.meta_title ?? "",
    meta_description: row?.meta_description ?? "",
    is_published: row?.is_published ?? true,
  }),
  toRowPayload: (values) => ({ ...values }),
};
